image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Ganache
    command: |
      echo "🛠️ Installing Ganache globally..."
      npm install ganache --global
  
  - name: Run npm install
    command: |
      echo "🛠️ Running npm install..."
      npm install