image:
  file: .gitpod.Dockerfile

tasks:

  - name: Install Truffle
    command: |
      npm install truffle --global && echo "🎉 Truffle installed"
  
  - name: Install Ganache
    command: |
      npm install ganache --global && echo "🎉 Ganache installed"

  - name: Run npm install
    command: |
      npm install && echo "🎉 Dependencies installed"

