// This will be generated by anchor build
// For now, placeholder structure
export const IDL = {
  version: "0.1.0",
  name: "tasksama",
  instructions: [
    {
      name: "initialize",
      accounts: [
        { name: "platformConfig", isMut: true, isSigner: false },
        { name: "authority", isMut: true, isSigner: true },
        { name: "feeRecipient", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "feePercentage", type: "u16" },
        { name: "minimumReward", type: "u64" },
      ],
    },
    {
      name: "createTask",
      accounts: [
        { name: "platformConfig", isMut: true, isSigner: false },
        { name: "task", isMut: true, isSigner: false },
        { name: "creator", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "rewardAmount", type: "u64" },
      ],
    },
    {
      name: "participate",
      accounts: [
        { name: "task", isMut: true, isSigner: false },
        { name: "participantRecord", isMut: true, isSigner: false },
        { name: "participant", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "markVideoUploaded",
      accounts: [
        { name: "participantRecord", isMut: true, isSigner: false },
        { name: "task", isMut: false, isSigner: false },
        { name: "participant", isMut: false, isSigner: true },
      ],
      args: [{ name: "videoHash", type: "string" }],
    },
    {
      name: "moderateVideo",
      accounts: [
        { name: "platformConfig", isMut: false, isSigner: false },
        { name: "participantRecord", isMut: true, isSigner: false },
        { name: "task", isMut: false, isSigner: false },
        { name: "moderator", isMut: false, isSigner: true },
      ],
      args: [{ name: "approved", type: "bool" }],
    },
    {
      name: "chooseWinner",
      accounts: [
        { name: "platformConfig", isMut: true, isSigner: false },
        { name: "task", isMut: true, isSigner: false },
        { name: "winnerRecord", isMut: false, isSigner: false },
        { name: "creator", isMut: true, isSigner: true },
        { name: "winner", isMut: true, isSigner: false },
        { name: "feeRecipient", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "ipfsMetadataUrl", type: "string" },
        { name: "ipfsVideoUrl", type: "string" },
      ],
    },
    {
      name: "cancelTask",
      accounts: [
        { name: "task", isMut: true, isSigner: false },
        { name: "creator", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "PlatformConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "authority", type: "publicKey" },
          { name: "feeRecipient", type: "publicKey" },
          { name: "feePercentage", type: "u16" },
          { name: "minimumReward", type: "u64" },
          { name: "totalTasksCreated", type: "u64" },
          { name: "totalTasksCompleted", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Task",
      type: {
        kind: "struct",
        fields: [
          { name: "taskId", type: "u64" },
          { name: "creator", type: "publicKey" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "rewardAmount", type: "u64" },
          { name: "feeAmount", type: "u64" },
          { name: "status", type: { defined: "TaskStatus" } },
          { name: "createdAt", type: "i64" },
          { name: "completedAt", type: { option: "i64" } },
          { name: "participantCount", type: "u32" },
          { name: "winner", type: { option: "publicKey" } },
          { name: "ipfsMetadataUrl", type: { option: "string" } },
          { name: "ipfsVideoUrl", type: { option: "string" } },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "ParticipantRecord",
      type: {
        kind: "struct",
        fields: [
          { name: "taskId", type: "u64" },
          { name: "participant", type: "publicKey" },
          { name: "participatedAt", type: "i64" },
          { name: "videoUploaded", type: "bool" },
          { name: "videoHash", type: { option: "string" } },
          { name: "videoModerated", type: { defined: "ModerationStatus" } },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  types: [
    {
      name: "TaskStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Active" },
          { name: "Completed" },
          { name: "Cancelled" },
        ],
      },
    },
    {
      name: "ModerationStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Approved" },
          { name: "Rejected" },
        ],
      },
    },
  ],
  events: [
    {
      name: "TaskCreatedEvent",
      fields: [
        { name: "taskId", type: "u64", index: false },
        { name: "creator", type: "publicKey", index: false },
        { name: "title", type: "string", index: false },
        { name: "rewardAmount", type: "u64", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "TaskCompletedEvent",
      fields: [
        { name: "taskId", type: "u64", index: false },
        { name: "winner", type: "publicKey", index: false },
        { name: "rewardAmount", type: "u64", index: false },
        { name: "ipfsMetadataUrl", type: "string", index: false },
        { name: "ipfsVideoUrl", type: "string", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: "RewardTooLow", msg: "Reward amount is below minimum required" },
    { code: 6001, name: "TitleTooLong", msg: "Title is too long (max 200 characters)" },
    { code: 6002, name: "DescriptionTooLong", msg: "Description is too long (max 1000 characters)" },
    { code: 6003, name: "TaskNotActive", msg: "Task is not active" },
    { code: 6004, name: "CreatorCannotParticipate", msg: "Creator cannot participate in their own task" },
    { code: 6005, name: "NotParticipant", msg: "User is not a participant of this task" },
    { code: 6006, name: "VideoNotApproved", msg: "Video has not been approved by moderators" },
    { code: 6007, name: "TaskNotCompleted", msg: "Task is not completed" },
    { code: 6008, name: "Unauthorized", msg: "Unauthorized action" },
  ],
}

export type Tasksama = typeof IDL
