name: Update Docker Container

# "push" events includes "merge" events from test into main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/fetch Repository 
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}

          # Add any additional SSH options if required

          # Stop and remove the existing container, then pull latest image, then run it with parameters
          # Adjust the image name, ports, and other parameters as needed
          script: |
            sudo docker stop task-sama
            sudo docker rm task-sama
            sudo docker pull task-sama:latest
            sudo docker run -d --name task-sama-production -p 3000:3000 -p 27017:27017 task-sama:latest

            
