name: Update Docker Container

# "push" events includes "merge" events from test into main
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/fetch Repository 
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}

        # Stop and remove the existing container, then pull latest image, then run it with parameters
      - name: Replace container
        run: |
          docker stop task-sama-backend
          docker rm task-sama-backend
          docker pull task-sama-backend:latest
          docker run -d --name task-sama-backend -p 3000:3000 task-sama-backend:latest

            
