name: Deploy backend container

# "push" events includes "merge" events from test into main
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/fetch Repository 
        uses: actions/checkout@v3

      - name: Replace container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          #password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            PASSWORD="${{ secrets.VPS_PASSWORD }}"
            CONTAINER_NAME="backend"
            echo "${PASSWORD}" | sudo -S docker stop ${CONTAINER_NAME} || true
            echo "${PASSWORD}" | sudo -S docker rm ${CONTAINER_NAME} || true
            echo "${PASSWORD}" | sudo -S docker pull crosta/ts-backend:latest
            echo "${PASSWORD}" | sudo -S docker run -d --name ${CONTAINER_NAME} -p 3000:3000 crosta/ts-backend:latest

            
