name: Update Docker Container

# "push" events includes "merge" events from test into main
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/fetch Repository 
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        # Stop and remove the existing container, then pull latest image, then run it with parameters
      - name: Replace container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          run: |
            docker stop crosta/ts-backend:latest
            docker rm crosta/ts-backend:latest
            docker pull crosta/ts-backend:latest
            docker run -d --name crosta/ts-backend:latest -p 3000:3000 crosta/ts-backend:latest

            
